[[headers]]
  for = "/*"
  [headers.values] 
  # COMMENT: Multi-key header rules are expressed with multi line strings
  Link = '''
  </tufte.min.css>; rel=preload; as=stylesheet, \
  </contact.css>; rel=preload; as=stylesheet, \
  </red.css>; rel=preload; as=stylesheet, \
  </latex.css>; rel=preload; as=stylesheet'''

[[redirects]]
   from   = "/*"
   to     = "/chat"
   status = 301
